### ISSUE TITLE
我这边 使用 Assgin 出现类似的错误，我该怎么办

### ISSUE THREAD

**Issue by sjyttkl** [cnbluegeek/cnbluegeek.github.io#1]
我这边 使用 Assgin 出现类似的错误，我改怎么修改你提供的代码呢？

`gd = sess.graph.as_graph_def()
for node in gd.node:
    if node.op == 'RefSwitch':
        node.op = 'Switch'
        for index in xrange(len(node.input)):
            if 'moving_' in node.input[index]:
                node.input[index] = node.input[index] + '/read'
    elif node.op == 'AssignSub':
        node.op = 'Sub'
        if 'use_locking' in node.attr: del node.attr['use_locking']
    elif node.op == 'AssignAdd':
        node.op = 'Add'
        if 'use_locking' in node.attr: del node.attr['use_locking']`

**Comment by jielyu** [comment]
直接使用这段代码报什么错呢？

可以提供一下具体的问题描述，包括操作系统，python版本，tensorflow版本，报错信息等等

**Comment by sjyttkl** [comment]
唉，我已经解决了。
